version: '3.8'

services:
  php-fpm:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build: 
      context: ./.docker/php-fpm
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - ./app/html:/var/www/html
    networks:
      - network
      - mongo
      - mysql

  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app/html:/var/www/html
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - network
      - mongo
      - mysql
    depends_on:
      - php-fpm

  webpack:
    container_name: ${COMPOSE_PROJECT_NAME}_webpack
    build: 
      context: ./.docker/webpack
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment: 
      - APP_ENV=${APP_ENV}
    volumes:
      - ./app/html:/var/www/html
    ports:
      - "3000:3000"

networks:
  network:
    driver: bridge
  mongo:
    external: true
    name: mongo_default
  mysql:
    external: true
    name: mysql_default
