version: '3'

services:
  web:
    container_name: ${COMPOSE_PROJECT_NAME}_web
    image: jflahaut/nginx-php:8.2
    environment: 
      - USER_ID=${USER_ID:-0}
      - GROUP_ID=${GROUP_ID:-0}
    volumes:
      - ./app/html:/var/www/html
    networks:
      - antibes
    ports:
      - 11000:80
    labels:
      - "traefik.enable=false"
      - "traefik.http.routers.web.rule=Host(`covid.dev-fullstack.net`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"

  inertia:
    container_name: ${COMPOSE_PROJECT_NAME}_inertia
    build: 
      context: ./.docker/inertia
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    environment: 
      - APP_ENV=${APP_ENV}
      - USER_ID=${USER_ID:-0}
      - GROUP_ID=${GROUP_ID:-0}
    volumes:
      - ./app/html:/var/www/html
    networks:
      - antibes
    labels:
      - "traefik.enable=false"

networks:
  antibes:
    external: true
    name: antibes
